### PR TITLE
Bump Surelog

### PR DESCRIPTION
**Pull request by RRozak**

### CODE REVIEW

**Comment by RRozak** [comment]
Error from csrng_core can be reproduced by https://github.com/chipsalliance/UHDM-integration-tests/pull/660

**Comment by RRozak** [comment]
I found another examples: https://github.com/chipsalliance/UHDM-integration-tests/pull/661
The issue is already risen: https://github.com/chipsalliance/Surelog/issues/2468

**Comment by RRozak** [comment]
The warning can be reproduced by https://github.com/chipsalliance/UHDM-integration-tests/pull/662

**Comment by RRozak** [comment]
Test of pinmux can be enabled again and this module can be moved to shared list.

**Review by rkapuscik — APPROVED** [review]

**Pull request merged**
